### ISSUE TITLE
Add catkin_lint

### ISSUE THREAD

**Issue by 130s** [ros-planning/moveit_ci#11]
e.g. Malformatted package.xml https://github.com/ros-planning/moveit_msgs/pull/26#discussion_r75628563 wasn't captured so far at anywhere in Pull Request --> ros.org Release pipeline afaik. 

Having an optional job to run `catkin_lint` in CI may be one way to solve it.

cf. Related discussion https://github.com/ros-industrial/industrial_ci/issues/58

**Comment by v4hn** [comment]
+2

But this makes only sense *after* the rest of MoveIt! has been linted (We will see how far people get tomorrow).

**Comment by davetcoleman** [comment]
+1 to running ``catkin_lint`` as a CI test.

**Comment by rhaschke** [comment]
+1

**Comment by rhaschke** [comment]
We have this since #45 :tada:
