### ISSUE TITLE
Add clang-tidy

### ISSUE THREAD

**Issue by scottpaulin** [ros-planning/moveit_ci#12]
There is a [moveit issue](https://github.com/ros-planning/moveit/issues/28) to run clang-tidy on pull requests. Should it be run automatically in the CI?

**Comment by davetcoleman** [comment]
We would like to setup it up now, but I don't think we can actually turn it on for all packages until we fix current clang-tidy problems.

**Comment by rhaschke** [comment]
Addressed via #45.
