### ISSUE TITLE
catkin_lint test report error for the depends on 3rd party source code package

### ISSUE THREAD

**Issue by RoboticsYY** [ros-planning/moveit_ci#80]
Recently we tried to use moveit_ci with our random_pick application that is to be added in a [PR](https://github.com/ros-planning/moveit_example_apps/pull/5) to the [moveit_example_apps](https://github.com/ros-planning/moveit_example_apps) project. Since the application depends on a 3rd party package "gpd", but it is not in the release of ros-melodic-* or other binary form. The catkin_lint test reports error on it. Please check [here](https://travis-ci.org/RoboticsYY/moveit_example_apps/jobs/562972374) for the result. 

Since catkin_lint test is implemented before a ros workspace is prepared, the "gpd" added in a .rosinstall file seems not possible to fix this. Another thought is to use `before_script` or a custom docker container with "gpd" installed, and use `CI_SOURCE_PATH` to bring the "gpd" to the catkin_lint test. But this will also enable clang-format test for "gpd", and it is not supposed to pass. 

Currently, seems all ways are blocked in front of me. Is there some methods could get the catkin_lint test pass?

**Comment by rhaschke** [comment]
Sorry for the late reply: I was on holidays.
I prepared a fix for this in #84 and pushed a commit to your PR https://github.com/ros-planning/moveit_example_apps/pull/5 to test it there. This additional commit should be removed if #84 is merged here.
