### ISSUE TITLE
Update README.md example travis config

### ISSUE THREAD

**Issue by davetcoleman** [ros-planning/moveit_ci#88]
It appears out of date from best practices, such as missing ``DOCKER_IMAGE`` parameter

**Comment by rhaschke** [comment]
I wouldn't declare the old approach of defining `ROS_DISTRO` and `ROS_REPO` as outdated.
We just added an alternative approach, using `DOCKER_IMAGE`. However, this one is already mentioned as an alternative in section [configurations](https://github.com/ros-planning/moveit_ci#configurations). So, I'm closing this here.
@davetcoleman, please feel free to re-open if you are missing anything else.
